enum ErrorTypes {
  DATABASE_ERROR = "DATABASE_ERROR",
  NOT_FOUND_ERROR = "NOT_FOUND_ERROR",
  BAD_REQUEST_ERROR = "BAD_REQUEST_ERROR",
  UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  CONFLICT_ERROR = "CONFLICT_ERROR",
  FORBIDDEN_ERROR = "FORBIDDEN_ERROR",
  SERVICE_UNAVAILABLE_ERROR = "SERVICE_UNAVAILABLE_ERROR",
  TIMEOUT_ERROR = "TIMEOUT_ERROR",
  PAYMENT_REQUIRED_ERROR = "PAYMENT_REQUIRED_ERROR",
}
